language: clojure
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
script: lein do test, cljfmt check
notifications:
    slack: bitmaker:1KC4HkuyKvjvxcPAFi1qaDQj
    webhooks:
      urls:
        - https://webhooks.gitter.im/e/6b4a3c7e90dff83f72b2
